language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4" 
after_success:
  - export AWCOORDINATES_COV=1
  - ./node_modules/.bin/jscoverage lib lib-cov
  - ./node_modules/.bin/mocha -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js